cd build
./test_nam ~/quartz-artifact/nam-benchmarks/adder_8.qasm --output ~/quartz-artifact/nam-benchmarks/adder_8.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/adder_8.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/barenco_tof_3.qasm --output ~/quartz-artifact/nam-benchmarks/barenco_tof_3.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/barenco_tof_3.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/barenco_tof_4.qasm --output ~/quartz-artifact/nam-benchmarks/barenco_tof_4.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/barenco_tof_4.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/barenco_tof_5.qasm --output ~/quartz-artifact/nam-benchmarks/barenco_tof_5.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/barenco_tof_5.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/barenco_tof_10.qasm --output ~/quartz-artifact/nam-benchmarks/barenco_tof_10.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/barenco_tof_10.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/csla_mux_3.qasm --output ~/quartz-artifact/nam-benchmarks/csla_mux_3.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/csla_mux_3.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/csum_mux_9.qasm --output ~/quartz-artifact/nam-benchmarks/csum_mux_9.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/csum_mux_9.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/gf2^4_mult.qasm --output ~/quartz-artifact/nam-benchmarks/gf2^4_mult.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/gf2^4_mult.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/gf2^5_mult.qasm --output ~/quartz-artifact/nam-benchmarks/gf2^5_mult.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/gf2^5_mult.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/gf2^6_mult.qasm --output ~/quartz-artifact/nam-benchmarks/gf2^6_mult.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/gf2^6_mult.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/gf2^7_mult.qasm --output ~/quartz-artifact/nam-benchmarks/gf2^7_mult.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/gf2^7_mult.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/gf2^8_mult.qasm --output ~/quartz-artifact/nam-benchmarks/gf2^8_mult.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/gf2^8_mult.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/gf2^9_mult.qasm --output ~/quartz-artifact/nam-benchmarks/gf2^9_mult.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/gf2^9_mult.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/gf2^10_mult.qasm --output ~/quartz-artifact/nam-benchmarks/gf2^10_mult.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/gf2^10_mult.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/mod5_4.qasm --output ~/quartz-artifact/nam-benchmarks/mod5_4.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/mod5_4.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/mod_mult_55.qasm --output ~/quartz-artifact/nam-benchmarks/mod_mult_55.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/mod_mult_55.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/mod_red_21.qasm --output ~/quartz-artifact/nam-benchmarks/mod_red_21.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/mod_red_21.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/qcla_adder_10.qasm --output ~/quartz-artifact/nam-benchmarks/qcla_adder_10.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/qcla_adder_10.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/qcla_com_7.qasm --output ~/quartz-artifact/nam-benchmarks/qcla_com_7.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/qcla_com_7.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/qcla_mod_7.qasm --output ~/quartz-artifact/nam-benchmarks/qcla_mod_7.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/qcla_mod_7.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/rc_adder_6.qasm --output ~/quartz-artifact/nam-benchmarks/rc_adder_6.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/rc_adder_6.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/tof_3.qasm --output ~/quartz-artifact/nam-benchmarks/tof_3.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/tof_3.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/tof_4.qasm --output ~/quartz-artifact/nam-benchmarks/tof_4.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/tof_4.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/tof_5.qasm --output ~/quartz-artifact/nam-benchmarks/tof_5.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/tof_5.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/tof_10.qasm --output ~/quartz-artifact/nam-benchmarks/tof_10.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/tof_10.log.nam &
./test_nam ~/quartz-artifact/nam-benchmarks/vbe_adder_3.qasm --output ~/quartz-artifact/nam-benchmarks/vbe_adder_3.qasm.output.nam --early-stop > ~/quartz-artifact/nam-benchmarks/vbe_adder_3.log.nam &